name: lz4-flex-rb

type: ruby

up:
  - ruby
  - bundler
  - rust

commands:
  build:
    desc: Build the gem using rake build
    run: bin/rake compile
  test:
    desc: Run tests
    syntax:
      argument: file
      optional: args...
    run:  |
      /opt/dev/bin/dev build
      if [[ $# -eq 0 ]]; then
        bin/test
      else
        bin/test "$@"
      fi
  style:
    desc: Run format
    aliases: [fmt]
    run: bin/rubocop -A && cargo clippy --fix --allow-dirty --allow-staged
