# typed: strict
# DO NOT EDIT MANUALLY
# This is an autogenerated file for explicit gem requires.
# Please instead update this file by running `bin/tapioca require`.
# frozen_string_literal: true

require "minitest/autorun"
require "sorbet-runtime"
