// Generated by BoltFFI — do not edit.
#include "ruby.h"
#include "ruby/encoding.h"
#include "ruby/ractor.h"
#include <stdint.h>
#include <limits.h>
#include <string.h>

typedef struct { const uint8_t *ptr; uintptr_t len; } FfiString;
typedef struct { const uint8_t *ptr; uintptr_t len; } FfiBytes;
typedef struct { uint8_t *ptr; uintptr_t len; uintptr_t cap; uintptr_t align; } FfiBuf;
extern void boltffi_free_buf(FfiBuf);

static inline FfiString bolt_rb_to_ffi_string(VALUE v) {
    FfiString s; s.ptr = (const uint8_t*)RSTRING_PTR(v); s.len = (uintptr_t)RSTRING_LEN(v); return s;
}
static inline FfiBytes bolt_rb_to_ffi_bytes(VALUE v) {
    FfiBytes b; b.ptr = (const uint8_t*)RSTRING_PTR(v); b.len = (uintptr_t)RSTRING_LEN(v); return b;
}

static inline int bolt_rb_to_ffi_bool(VALUE v) {
    if (v != Qtrue && v != Qfalse) {
        rb_raise(rb_eTypeError, "expected true or false");
    }
    return v == Qtrue;
}


typedef struct VarInt VarInt;

static VALUE c_boltffi_ruby_var_int;
static const rb_data_type_t boltffi_ruby_var_int_type;

static void boltffi_ruby_var_int_dfree(void *p) {
    if (p != NULL) {
        extern void boltffi_var_int_free(VarInt*);
        boltffi_var_int_free((VarInt*)p);
    }
}

static const rb_data_type_t boltffi_ruby_var_int_type = {
    "lz4_flex_ext::VarInt",
    { NULL, boltffi_ruby_var_int_dfree, NULL, NULL },
    NULL, NULL, RUBY_TYPED_FREE_IMMEDIATELY,
};


extern FfiBuf boltffi_compress(FfiBytes, uint8_t);
extern FfiBuf boltffi_decompress(FfiBytes);
extern uint8_t boltffi_get_compressed_encoding(FfiBytes);
extern uint32_t boltffi_get_decompressed_size(FfiBytes);


extern FfiBuf boltffi_var_int_compress(FfiBytes);
extern FfiBuf boltffi_var_int_decompress(FfiBytes);


static VALUE boltffi_ruby_var_int_alloc(VALUE klass) {
    return TypedData_Wrap_Struct(klass, &boltffi_ruby_var_int_type, NULL);
}


static VALUE boltffi_ruby_var_int_boltffi_ruby_compress(VALUE self, VALUE boltffi_ruby_input) {
    (void)self; // static method: `self` is the class object, unused
    Check_Type(boltffi_ruby_input, T_STRING);
    FfiBuf _ffi_ret = boltffi_var_int_compress(bolt_rb_to_ffi_bytes(boltffi_ruby_input));
    // Vec<u8> returns a raw (non-wire-encoded) FfiBuf: ptr/len describe the bytes
    // directly, with no 4-byte length prefix (unlike String's wire_encode buffer).
    { VALUE _rb_ret = rb_str_new((const char*)_ffi_ret.ptr, (long)_ffi_ret.len);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE boltffi_ruby_var_int_boltffi_ruby_decompress(VALUE self, VALUE boltffi_ruby_input) {
    (void)self; // static method: `self` is the class object, unused
    Check_Type(boltffi_ruby_input, T_STRING);
    FfiBuf _ffi_ret = boltffi_var_int_decompress(bolt_rb_to_ffi_bytes(boltffi_ruby_input));
    // Vec<u8> returns a raw (non-wire-encoded) FfiBuf: ptr/len describe the bytes
    // directly, with no 4-byte length prefix (unlike String's wire_encode buffer).
    { VALUE _rb_ret = rb_str_new((const char*)_ffi_ret.ptr, (long)_ffi_ret.len);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}



static VALUE boltffi_ruby_compress(VALUE self, VALUE boltffi_ruby_input, VALUE boltffi_ruby_encoding_val) {
    Check_Type(boltffi_ruby_input, T_STRING);
    FfiBuf _ffi_ret = boltffi_compress(bolt_rb_to_ffi_bytes(boltffi_ruby_input), NUM2UINT(boltffi_ruby_encoding_val));
    // Vec<u8> returns a raw (non-wire-encoded) FfiBuf: ptr/len describe the bytes
    // directly, with no 4-byte length prefix (unlike String's wire_encode buffer).
    { VALUE _rb_ret = rb_str_new((const char*)_ffi_ret.ptr, (long)_ffi_ret.len);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE boltffi_ruby_decompress(VALUE self, VALUE boltffi_ruby_input) {
    Check_Type(boltffi_ruby_input, T_STRING);
    FfiBuf _ffi_ret = boltffi_decompress(bolt_rb_to_ffi_bytes(boltffi_ruby_input));
    // Vec<u8> returns a raw (non-wire-encoded) FfiBuf: ptr/len describe the bytes
    // directly, with no 4-byte length prefix (unlike String's wire_encode buffer).
    { VALUE _rb_ret = rb_str_new((const char*)_ffi_ret.ptr, (long)_ffi_ret.len);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE boltffi_ruby_get_compressed_encoding(VALUE self, VALUE boltffi_ruby_input) {
    Check_Type(boltffi_ruby_input, T_STRING);
    uint8_t _ffi_ret = boltffi_get_compressed_encoding(bolt_rb_to_ffi_bytes(boltffi_ruby_input));
    return rb_uint2inum((uintptr_t)_ffi_ret);

}
static VALUE boltffi_ruby_get_decompressed_size(VALUE self, VALUE boltffi_ruby_input) {
    Check_Type(boltffi_ruby_input, T_STRING);
    uint32_t _ffi_ret = boltffi_get_decompressed_size(bolt_rb_to_ffi_bytes(boltffi_ruby_input));
    return rb_uint2inum((uintptr_t)_ffi_ret);

}

void Init_lz4_flex_ext_native(void) {
    // Declare every method defined below safe to call from any Ractor.
    // Opt-in (`[targets.ruby] ractor_safe`): asserts the bound Rust crate has no
    // unsynchronized global mutable state. Must precede the rb_define_* calls.
    rb_ext_ractor_safe(true);
    VALUE mod = rb_define_module("Lz4FlexExt");
    VALUE native = rb_define_module_under(mod, "Native");

    c_boltffi_ruby_var_int = rb_define_class_under(mod, "VarInt", rb_cObject);
    rb_define_alloc_func(c_boltffi_ruby_var_int, boltffi_ruby_var_int_alloc);
    rb_define_singleton_method(c_boltffi_ruby_var_int, "compress", boltffi_ruby_var_int_boltffi_ruby_compress, 1);
    rb_define_singleton_method(c_boltffi_ruby_var_int, "decompress", boltffi_ruby_var_int_boltffi_ruby_decompress, 1);


    rb_define_module_function(native, "compress", boltffi_ruby_compress, 2);
    rb_define_module_function(native, "decompress", boltffi_ruby_decompress, 1);
    rb_define_module_function(native, "get_compressed_encoding", boltffi_ruby_get_compressed_encoding, 1);
    rb_define_module_function(native, "get_decompressed_size", boltffi_ruby_get_decompressed_size, 1);

}