[package]
name = "lz4_flex_ext"
version = "0.1.0"
edition = "2021"
authors = ["Ian Ker-Seymer <ian.kerseymer@shopify.com>"]
license = "MIT"
publish = false
rust-version = "1.86.0"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
boltffi = "0.26.1"
lz4_flex = { version = "0.12.0", default-features = true }
postcard = "1.1.3"
serde = { version = "1.0.219", features = ["derive"] }
static_assertions = "1.1.0"
