# frozen_string_literal: true

# Generated by BoltFFI — do not edit.
require "fileutils"
require "tmpdir"

# ── make-time entry point: build the Rust staticlib, then exit ──────────────
# When no prebuilt archive is shipped, `make` re-invokes this very script (see
# the rule appended at the bottom) with $BOLTFFI_BUILD_STATICLIB set to the
# archive path it wants produced. Running the cargo build from `make` — not at
# configure time — keeps it on the same footing as a normal C compile: it
# honors $CARGO/$RUSTFLAGS, participates in `make`/`make clean`, and runs under
# rake-compiler(-dock) cross builds.
#
# Robust by construction: force the crate-type at the CLI (so the crate's
# Cargo.toml need not declare `staticlib`), pin the manifest by absolute path,
# and read the produced archive's path straight from cargo's JSON output —
# never reconstruct `target/release/...`, which breaks under custom profiles,
# CARGO_TARGET_DIR, a renamed crate, or a custom [lib] name.
if (staticlib_out = ENV["BOLTFFI_BUILD_STATICLIB"])
  cargo = ENV.fetch("CARGO", "cargo")

  # Crate sources are located via $BOLTFFI_CRATE_MANIFEST, else the vendored
  # copy beside this extconf. (Source vendoring is a tracked follow-up; until
  # it lands, set BOLTFFI_CRATE_MANIFEST to the crate's Cargo.toml.)
  manifest = File.expand_path(
    ENV["BOLTFFI_CRATE_MANIFEST"] || File.join(__dir__, "Cargo.toml"),
  )
  unless File.exist?(manifest)
    abort "boltffi: cannot build #{staticlib_out} from source — crate manifest " \
      "not found at #{manifest}. Set BOLTFFI_CRATE_MANIFEST to the crate's " \
      "Cargo.toml, or install a precompiled gem."
  end

  # Build into a throwaway target dir we own, so the (potentially large) cargo
  # build tree never lingers in the gem after install. Dir.mktmpdir removes it
  # on every exit path — including the aborts below (their SystemExit unwinds
  # through its ensure). The .a is copied out *before* the block ends, so it
  # survives the cleanup.
  produced = nil
  native_libs = nil
  Dir.mktmpdir("boltffi-lz4_flex_ext_ffi-") do |target_dir|
    # `--lib` pins the crate-type override to the library target — a crate may
    # also define bins/examples, and cargo refuses an ambiguous --crate-type.
    # `--print native-static-libs` rides along on the *same* compilation so we
    # capture the crate's exact transitive system libraries from rustc itself —
    # never a hardcoded guess. (A separate query would hit the build cache and
    # skip rustc, emitting no note, so it must be folded into the one build.)
    build = [
      cargo,
      "rustc",
      "--release",
      "--lib",
      "--manifest-path",
      manifest,
      "--target-dir",
      target_dir,
      "--crate-type",
      "staticlib",
      "--message-format",
      "json-render-diagnostics",
      "--",
      "--print",
      "native-static-libs",
    ]
    # Merge stderr into stdout: artifacts arrive as JSON (the .a path), while the
    # `native-static-libs:` note is a rendered diagnostic on stderr. Buffer the
    # whole stream so a failure can be replayed (stderr is no longer inherited).
    output = +""
    IO.popen(build, err: [:child, :out]) do |io|
      io.each_line do |line|
        output << line
        # Cargo emits one JSON object per line; we need only two things:
        # the .a path from compiler-artifact records, and the native-static-libs
        # note from stderr. Both are extractable with plain string matching —
        # no JSON parser needed (and no gem dependency).
        if line.include?('"reason":"compiler-artifact"')
          # Extract every quoted path ending in .a; last one wins (root crate's
          # artifact record comes last in cargo's output).
          line.scan(/"([^"]+\.a)"/) { |(path)| produced = path }
        elsif (idx = line.index("native-static-libs:"))
          # last occurrence wins (the root crate's), mirroring the .a rule
          native_libs = line[(idx + "native-static-libs:".length)..]
            .gsub(/\e\[[0-9;]*m/, "")
            .split
        end
      end
    end
    unless $?.success?
      $stderr.print(output)
      abort "boltffi: cargo failed to build the staticlib (see output above)"
    end
    unless produced && File.exist?(produced)
      abort "boltffi: cargo produced no .a staticlib for #{manifest} — does the " \
        "crate expose a lib target?"
    end

    FileUtils.cp(produced, staticlib_out)
    # Sidecar consumed by the Makefile's link step (see the injected rule). Write
    # it even when empty so the link is deterministic; warn if rustc emitted no
    # note (the link will then surface any missing-symbol error directly).
    if native_libs.nil?
      $stderr.puts "boltffi: warning — rustc emitted no native-static-libs note; " \
        "linking with no extra system libraries"
    end
    File.write("#{staticlib_out}.native-libs", Array(native_libs).join(" "))
  end
  exit 0
end

# ── configure time: wire up the build ──────────────────────────────────────
require "mkmf"

# Keep debug symbols in the compiled glue so crashes in the FFI boundary are
# debuggable; the symbol-hiding linker flags below trim the dynamic symbol
# table, not the DWARF info.
$CFLAGS << " -g"

# Two gem shapes share this extconf, distinguished by whether liblz4_flex_ext_ffi.a
# is already present next to it:
#   • Precompiled gem (`boltffi pack ruby`): ships a prebuilt, per-arch
#     liblz4_flex_ext_ffi.a — link it as-is, no toolchain needed.
#   • Source gem: no archive shipped — `make` compiles the staticlib from the
#     Rust crate (rule appended below), then links it.
# Linking the .a by absolute path (not -llz4_flex_ext_ffi) forces the static
# archive over any same-named shared object on the search path.
archive = File.join(__dir__, "liblz4_flex_ext_ffi.a")
build_from_source = !File.exist?(archive)

# Fail fast, during configure, if we'll need a toolchain at `make` time but
# don't have one — a clearer signal than a cargo-not-found error mid-build.
if build_from_source
  cargo = ENV.fetch("CARGO", "cargo")
  unless find_executable(cargo)
    abort "boltffi: `#{cargo}` not found on PATH — building lz4_flex_ext from " \
      "source needs a Rust toolchain (https://rustup.rs), or install a " \
      "precompiled gem that ships liblz4_flex_ext_ffi.a."
  end
end

$LOCAL_LIBS << " #{archive}"

# A Rust staticlib bundles all *Rust* code (incl. std/alloc/panic) but NOT its
# transitive *system* libraries — those must be supplied at link time. We never
# hardcode that set: rustc knows it exactly, so the build step above captures
# `--print native-static-libs` into a sidecar and the injected Makefile rule
# feeds it to the link (`$(LIBS)`, after the archive — correct ld order). A
# precompiled gem ships the same sidecar from `boltffi pack ruby`.
#
# These OS branches set only *linker behavior*, which is genuinely platform- (not
# crate-) specific and so can't come from native-static-libs:
#   • Symbol hiding — the load-bearing *safety* property, not an optimization. A
#     staticlib re-exports every symbol it contains, so two BoltFFI gems in one
#     process would otherwise collide on Rust's runtime symbols and cross-
#     interpose. Export only Init_ and hide the archive (`-exported_symbol` on
#     ld64, `--exclude-libs,ALL` on GNU ld).
#   • Dead-code stripping (`-dead_strip`/`--gc-sections`) then drops the Rust
#     code unreachable from Init_. Init_ is compiled from this gem's _native.c
#     (not the archive), so the hiding/stripping never touches it.
#
# Branch on the *target* OS (target_os, not host_os): under rake-compiler-dock
# cross builds, host_os is the build box, not the gem's target.
case RbConfig::CONFIG["target_os"]
when /darwin/
  $LDFLAGS << " -Wl,-exported_symbol,_Init_lz4_flex_ext_native"
  $LDFLAGS << " -Wl,-dead_strip"
when /linux|freebsd|openbsd|netbsd|mingw/
  # GNU ld / lld (FreeBSD, OpenBSD, NetBSD all ship lld which accepts these flags).
  # mingw targets (rake-compiler-dock Windows cross builds) use GNU ld-compatible tooling.
  $LDFLAGS << " -Wl,--exclude-libs,ALL"
  $LDFLAGS << " -Wl,--gc-sections"
when /mswin/
  # MSVC link.exe: /EXPORT controls the exported symbol set; /OPT:REF strips unreferenced code.
  $LDFLAGS << " /EXPORT:Init_lz4_flex_ext_native"
  $LDFLAGS << " /OPT:REF"
end

create_makefile("lz4_flex_ext_native")

# Inject into mkmf's Makefile rather than writing our own.
native_libs_file = "#{archive}.native-libs"
File.open("Makefile", "a") do |mf|
  # Feed the crate's exact native-static-libs into the link — never hardcoded.
  # The sidecar is written by the source build below, or shipped by `boltffi
  # pack ruby` for a precompiled gem. $(LIBS) is the last token on mkmf's link
  # line, so these land after the archive (the order order-sensitive ld wants).
  # `:=` snapshots mkmf's LIBS now; the recursive `=` defers `$(shell cat …)` to
  # link time, by which point the prerequisite below has written the sidecar.
  # Absent sidecar ⇒ empty ⇒ harmless (no extra libs).
  mf.puts
  mf.puts "# BoltFFI: link the crate's exact native-static-libs (from rustc), never hardcoded."
  mf.puts "BOLTFFI_NATIVE_LIBS_FILE = #{native_libs_file}"
  mf.puts "BOLTFFI_ORIG_LIBS := $(LIBS)"
  mf.puts "LIBS = $(BOLTFFI_ORIG_LIBS) $(shell cat \"$(BOLTFFI_NATIVE_LIBS_FILE)\" 2>/dev/null)"

  # The archive (and its sidecar) becomes a prerequisite of the link ($(DLLIB)),
  # built by re-invoking this script in build mode. The rule has *no* other
  # prerequisites, so `make` runs it only when the archive is absent — a
  # precompiled gem that ships liblz4_flex_ext_ffi.a is used as-is, cargo unrun.
  if build_from_source
    mf.puts
    mf.puts "# BoltFFI: build the Rust staticlib (+ native-libs sidecar) from source before linking."
    mf.puts "BOLTFFI_STATICLIB = #{archive}"
    mf.puts "$(DLLIB): $(BOLTFFI_STATICLIB)"
    mf.puts "$(BOLTFFI_STATICLIB):"
    mf.puts "\t$(Q) BOLTFFI_BUILD_STATICLIB=\"$@\" $(RUBY) \"$(srcdir)/extconf.rb\""
    mf.puts "clean-boltffi-staticlib:"
    mf.puts "\t-$(Q)$(RM) \"$(BOLTFFI_STATICLIB)\" \"$(BOLTFFI_NATIVE_LIBS_FILE)\""
    mf.puts "clean: clean-boltffi-staticlib"
  end
end
