---
name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        ruby: ["3.2", "3.3", "3.4", "ruby-head"]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: oxidize-rb/actions/setup-ruby-and-rust@d4731ac609739be0920f0faf5569b58b8eb1a262 # v1.4.0
        with:
          rustup-toolchain: "1.80.1"
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          cargo-cache: true
          cache-version: v1

      - name: Compile
        run: bundle exec rake compile:dev

      - name: Run ruby tests
        run: bin/test --reporter spec

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: oxidize-rb/actions/setup-ruby-and-rust@d4731ac609739be0920f0faf5569b58b8eb1a262 # v1.4.0
        with:
          rustup-toolchain: "1.80.1"
          ruby-version: "3.4"
          bundler-cache: true
          cargo-cache: true
          cache-version: v1

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Cargo
        run: cargo fmt --check

      - name: Rubocop
        run: bundle exec rake rubocop
